object Libs {
    private const val junitVersion = "5.4.0"
    const val junitApi = "org.junit.jupiter:junit-jupiter-api:$junitVersion"
    const val junitEngine = "org.junit.jupiter:junit-jupiter-engine:$junitVersion"
    const val guava = "com.google.guava:guava:27.0.1-jre"
    const val guice = "com.google.inject:guice:4.2.2"
    const val autoCommon = "com.google.auto:auto-common:0.10"
    private const val autoValueVersion = "1.6.3"
    const val autoValueAnnotations = "com.google.auto.value:auto-value-annotations:$autoValueVersion"
    const val autoValueProcessor = "com.google.auto.value:auto-value:$autoValueVersion"
    const val autoService = "com.google.auto.service:auto-service:1.0-rc4"
    const val javapoet = "com.squareup:javapoet:1.11.1"
    const val inject = "javax.inject:javax.inject:1"
    const val compileTesting = "com.google.testing.compile:compile-testing:0.15"
}
