object Libs {
    private const val junitVersion = "6.1.0"
    const val junitApi = "org.junit.jupiter:junit-jupiter-api:$junitVersion"
    const val junitEngine = "org.junit.jupiter:junit-jupiter-engine:$junitVersion"
    const val junitPlatformLauncher = "org.junit.platform:junit-platform-launcher:$junitVersion"
    const val guava = "com.google.guava:guava:33.6.0-jre"
    private const val kyoriAdventureVersion = "5.1.1"
    const val kyoriAdventure = "net.kyori:adventure-api:$kyoriAdventureVersion"
    const val kyoriAdventureTextPlain = "net.kyori:adventure-text-serializer-plain:$kyoriAdventureVersion"
    const val autoCommon = "com.google.auto:auto-common:1.2.2"
    private const val autoValueVersion = "1.11.1"
    const val autoValueAnnotations = "com.google.auto.value:auto-value-annotations:$autoValueVersion"
    const val autoValueProcessor = "com.google.auto.value:auto-value:$autoValueVersion"
    const val autoService = "com.google.auto.service:auto-service:1.1.1"
    const val javapoet = "com.squareup:javapoet:1.13.0"
    // Sync with Mojang's Log4j
    private const val log4jVersion = "2.26.0"
    const val log4jApi = "org.apache.logging.log4j:log4j-api:$log4jVersion"
    const val log4jCore = "org.apache.logging.log4j:log4j-core:$log4jVersion"
    const val javaxAnnotations = "com.google.code.findbugs:jsr305:3.0.2"
    const val compileTesting = "com.google.testing.compile:compile-testing:0.23.0"
    const val mockito = "org.mockito:mockito-core:5.23.0"
}
